# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish React Package

on:
  push:
    branches:
      - main
    paths:
      - "packages/react/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g pnpm # pnpm 설치
      - run: pnpm install
      - run: pnpm --filter @tiny-placeholder/react test

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Use Node LTS ✨
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install pnpm 📦️
        run: npm install -g pnpm # pnpm 설치

      - name: Install dependencies 📦️
        run: pnpm install

      - name: Build 🔨
        run: pnpm --filter @tiny-placeholder/react build

      - name: Publish 🚀
        run: pnpm --filter @tiny-placeholder/react publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
